<?php
include(TPLPATH.'/header.tpl.php');
?>
<link rel="stylesheet" href="<?=TPLURL?>/css/zhide-css.css"/>
<script src="<?=TPLURL?>/js/head.min.js"></script>
<script src="<?=TPLURL?>/js/zhidemai.js"></script>
<header> </header>
<script> 
$.ajaxSetup ({ 
    cache: false //关闭AJAX相应的缓存 
});
</script>
    
    <div class="zdm-body">
      <div class="zhidecontainer">

          
          <div class="zdm-uc-article yahei zdm-border">
            <h4 class="zdm-uc-title bold">
              <a href="" style="font-size:16px; text-decoration:underline">我要爆料</a>
            </h4>
            <ul id="J-arti-tabs" class="zdm-uc-tabs clearfix">
              <li class="current">
                我的爆料<span class="num">(<span class="bold J-vote-num">23</span>)</span>
              </li>
            </ul>
            <div id="J-arti-content">
            
            <div class="zdm-uc-arti-list clearfix">
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=23" class="blue" target="_blank">1苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=22" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=21" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=20" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=19" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=18" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=17" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=16" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=15" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=14" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=13" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=12" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=11" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=10" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=9" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=8" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=7" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=6" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=5" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="zdm-uc-arti-item J-zdm-uc-arti-item" data-id="128619"><dl><dt class="hd"><a href="http://fx.858zy.com/plugin.php?mod=zhidemai&act=view&id=4" class="blue" target="_blank">苏宁易购 PHILIPS 飞利浦 净水专场</a></dt><dd class="bd six"><span class="nine">推荐理由：</span><p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><strong>厨房必备，需要的朋友可考虑入手！</strong>乐扣乐扣酷菲偲刀具5件套，采用<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">德国进口不锈钢</span></strong>制作，含有3.5寸水果刀+8寸厨刀+6.5寸切片刀+8寸厨房多用剪+橡胶木刀座，<strong><span style="border-bottom:0px;border-left:0px;padding-bottom:0px;margin:0px;padding-left:0px;padding-right:0px;color:#e53333;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">从切水果到各种生熟食品，都可以满足，比较实用。</span></strong></span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;"><br />
</span>
</p>
<p style="border-bottom:0px;text-align:left;border-left:0px;padding-bottom:0px;widows:2;text-transform:none;background-color:#ffffff;text-indent:0px;margin:0px;padding-left:0px;padding-right:0px;font:13px/25px 'Hiragino Sans GB', 'Microsoft YaHei', SimSun, sans-serif;white-space:normal;orphans:2;letter-spacing:normal;color:#555555;border-top:0px;border-right:0px;word-spacing:0px;padding-top:0px;-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;">
	<span style="border-bottom:0px;border-left:0px;padding-bottom:0px;line-height:1.5;margin:0px;padding-left:0px;padding-right:0px;font-size:13px;border-top:0px;border-right:0px;padding-top:0px;">精铸钢头设计，增加刀体本身的重量，切割食材更轻松；45°刀背磨抛，使用更安全；ABS防滑手柄设计，手感舒适；特有的钢头设计，防止使用时被刀刃尾部割伤；人性化的指掌设计，使用更舒适。</span>
</p></dd><dd class="ft nine">2014-03-18 08:33:34</dd></dl><div class="zdm-uc-arti-status"><!-- 未审核 --><span style=" color:green">通过</span></div></div>
                        <div class="pages zdm-pages">
            <span class='disabled'>1-20/23 记录</span><span class='disabled'>1/2 页</span><a href='http://fx.858zy.com/plugin.php?mod=zhidemai&act=user&page=1'>首页</a><a href='http://fx.858zy.com/plugin.php?mod=zhidemai&act=user&page=0'><</a><span class="current">1</span><a href='http://fx.858zy.com/plugin.php?mod=zhidemai&act=user&page=2'>2</a><a href='http://fx.858zy.com/plugin.php?mod=zhidemai&act=user&page=2'>></a><a href='http://fx.858zy.com/plugin.php?mod=zhidemai&act=user&page=2'>尾页</a>            </div>
            </div>
            </div>
          </div>

              </div>
    </div>
       
    
    
    <!--评价本文投票提示-->
